name: Yield curve

on:
  workflow_dispatch:
  schedule:
    - cron: '00 10 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget
    - name: Restore dependencies
      run: dotnet restore

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Pip install
      run: pip install -I matplotlib

    - name: Build
      run: dotnet build --no-restore --configuration Release
    - shell: bash
      env: 
        PYTHON_INTERPRETER:  python
        TELEGRAM_BOT_TOKEN:  ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_SUBSCRIBER_ID:  ${{ secrets.TELEGRAM_SUBSCRIBER_ID }}
      run: dotnet run --no-build --configuration Release --project MyMarketBot -zcyc
